baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Harsh Malik"
theme = "PaperMod"


[pagination]
  pagerSize = 10


[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowToc = false

[params.homeInfoParams]
  Title = "Hi, I'm Harsh"
  Content = "CITI • CFA Level II Cleared • Curiosity-driven ML & AI research • Data, Finance & Python builder"

[[params.socialIcons]]
    name = "github"
    url  = "https://github.com/godhunter98"

[[params.socialIcons]]
    name = "linkedin"
    url  = "https://linkedin.com/in/harshmalik98"

[menu]

  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 4

  [[menu.main]]
    name = "Projects"
    url  = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2