baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Nano Labs"
theme = "PaperMod"


[pagination]
  pagerSize = 10


[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowToc = false
  mainSections = ["blog"]


[[params.socialIcons]]
    name = "github"
    url  = "https://github.com/godhunter98"

[[params.socialIcons]]
    name = "linkedin"
    url  = "https://linkedin.com/in/harshmalik98"

[menu]

  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url  = "/projects/"
    weight = 2

  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 3

  


[markup]
  [markup.goldmark.renderer]
    unsafe = true